vim.cmd('filetype plugin indent on') -- auto-indent plugins and filetypes to allow correct indentation
vim.o.shortmess = vim.o.shortmess .. 'c' -- display fewer messages
vim.o.hidden = true -- move between open buffers without saving current buffer
vim.o.whichwrap = 'b,s,<,>,[,],h,l' -- allows the cursor to move to the next line when at the beginning or end of the current line
vim.o.pumheight = 10 -- sets the height of the autocomplete picklist
vim.o.fileencoding = 'utf-8' -- file character encoding
vim.o.cmdheight = 2 -- command line height
vim.o.splitbelow = true -- opens new windows below the current window
vim.o.splitright = true -- opens new windows to the right of the current window
vim.opt.termguicolors = true -- enable the use of colors for the terminal
vim.o.conceallevel = 0 -- disables the text hiding feature
vim.o.showtabline = 2 -- always show the tabline (even when only one tab is open)
vim.o.showmode = true -- show the current mode in nvim
vim.o.backup = false -- don't create backups before overwriting files
vim.o.writebackup = false -- don't backup files before overwriting them
vim.o.updatetime = 300 -- set the time (in milliseconds) for writing the swap file and triggering CursorHold/CursorHoldI autocmds
vim.o.timeoutlen = 100 -- set the time (in milliseconds) for which mappings are waited for
vim.o.clipboard = "unnamedplus" -- use the system clipboard for yanking and pasting
vim.o.hlsearch = false -- don't highlight search results
vim.o.ignorecase = true -- ignore case when searching
vim.o.scrolloff = 3 -- number of lines to keep in view above/below cursor when scrolling
vim.o.sidescrolloff = 5 -- number of columns to keep in view to the left/right of cursor when scrolling horizontally
vim.o.mouse = "a" -- enables the use of the mouse
vim.wo.wrap = false -- disable line wrapping
vim.wo.number = true -- show line numbers
vim.o.cursorline = true -- highlight the current line
vim.wo.signcolumn = "yes" -- always show the signcolumn, even when there are no signs present
vim.o.tabstop = 2 -- set the width of a tab character
vim.bo.tabstop = 2 -- set the width of a tab character for the current buffer
vim.o.softtabstop = 2 -- set the number of spaces to be used for a soft tab
vim.o.shiftwidth = 2 -- set the number of spaces to be used for indentation
vim.bo.shiftwidth = 2 -- set the number of spaces to be used for indentation for the current buffer
vim.o.autoindent = true -- automatically indent new lines to match the indentation level of the previous line
vim.bo.autoindent = true -- automatically indent new lines to match the indentation level of the previous line for the current buffer
vim.o.expandtab = true -- use spaces instead of tabs for indentation
vim.bo.expandtab = true -- use spaces instead of tabs for indentation for the current buffer
